name: CI / Node Continuous Integration

on:
  pull_request:
    branches: [develop]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - run: npm run lint
      - run: npm run flow
      - run: npm run build
